name: 'Composer (php-actions)'
description: 'Use the Composer CLI in your Github Actions.'
inputs:
  command:
    description: 'Composer command to run'
    required: true
    default: install
  args:
    description: 'args to run'
    required: false

outputs:
  time:
    description: 'The time the action was run'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.args }}
branding:
  icon: 'package'  
  color: 'purple'
